/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_LODB_DIAGNOSTICS_PB_H_INCLUDED
#define PB_LODB_DIAGNOSTICS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* Optional diagnostics record type shipped with LoDB (nanopb bindings in-tree). */
typedef struct _lodb_DiagnosticsTest {
    uint32_t id;
    char value[64];
    uint32_t timestamp;
    bool active;
} lodb_DiagnosticsTest;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define lodb_DiagnosticsTest_init_default        {0, "", 0, 0}
#define lodb_DiagnosticsTest_init_zero           {0, "", 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define lodb_DiagnosticsTest_id_tag              1
#define lodb_DiagnosticsTest_value_tag           2
#define lodb_DiagnosticsTest_timestamp_tag       3
#define lodb_DiagnosticsTest_active_tag          4

/* Struct field encoding specification for nanopb */
#define lodb_DiagnosticsTest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   id,                1) \
X(a, STATIC,   SINGULAR, STRING,   value,             2) \
X(a, STATIC,   SINGULAR, UINT32,   timestamp,         3) \
X(a, STATIC,   SINGULAR, BOOL,     active,            4)
#define lodb_DiagnosticsTest_CALLBACK NULL
#define lodb_DiagnosticsTest_DEFAULT NULL

extern const pb_msgdesc_t lodb_DiagnosticsTest_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define lodb_DiagnosticsTest_fields &lodb_DiagnosticsTest_msg

/* Maximum encoded size of messages (where known) */
#define LODB_DIAGNOSTICS_PB_H_MAX_SIZE           lodb_DiagnosticsTest_size
#define lodb_DiagnosticsTest_size                79

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
